name: Upload Assets to AWS S3
# Deployes all the static assets (documents, images) to your own custom AWS S3 Bucket,
# Make sure to add appropriate aws secrets
# repository -> settings -> secrets

on:
  push:
    branches: [master]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        name: Deploy the assets/ folder to Amazon S3
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SOURCE_DIR: "assets/"

          name: Upload Website
